name: Upload Release Artifacts

on:
  release:
    types: [created]

jobs:
  build:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        platform:
          - { runner: windows-latest, name: windows }
          - { runner: macos-latest, name: mac }
          - { runner: ubuntu-20.04, name: linux }

    runs-on: ${{ matrix.platform.runner }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Build
      id: build
      run: |
        artifact=lunar-launcher-inject-${{ matrix.platform.name }}-${{ github.event.release.name }}${{ matrix.platform.name == 'windows' && '.exe' || '' }}
        echo "ARTIFACT=$artifact" >> $GITHUB_OUTPUT
        
        GOARCH=amd64 go build -v -ldflags '-s -w' -o $artifact

    - name: Upload Executable
      run: gh release upload ${GITHUB_REF_NAME} ${{ steps.build.outputs.ARTIFACT }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
